version: '3.7'

services:
  database:
    image: 'mysql:latest'
    container_name: database
    restart: always
    ports:
      - '3307:3306'
    networks:
      - backend_net
    environment:
      MYSQL_DATABASE: itbkk-kk3
      MYSQL_USER: gpm
      MYSQL_PASSWORD: gpm@password
      MYSQL_ROOT_PASSWORD: gpm
    volumes:
      - ./database/data:/var/lib/mysql/
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/my.cnf:/etc/my.cnf

  backend:
    build: ./backend
    container_name: backend
    restart: always
    networks:
      - backend_net
      - frontend_net
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=itbkk-kk3
      - DB_USER=gpm
      - DB_PASS=gpm@password

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - frontend_net
    depends_on:
      - backend

  proxy:
    image: "nginx:alpine"
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./cert/privkey.pem:/etc/ssl/private/privkey.pem
      - ./cert/ddns.net.pem:/etc/ssl/certs/ddns.net.pem
    depends_on:
      - frontend
    networks:
      - frontend_net

networks:
  backend_net:
  frontend_net:
