-- MySQL Script generated by MySQL Workbench
-- Sat Sep 28 14:42:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema itbkk-kk3
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `itbkk-kk3` ;

-- -----------------------------------------------------
-- Schema itbkk-kk3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `itbkk-kk3` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `itbkk-kk3` ;

-- -----------------------------------------------------
-- Table `itbkk-kk3`.`board_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `itbkk-kk3`.`board_permissions` ;

CREATE TABLE IF NOT EXISTS `itbkk-kk3`.`board_permissions` (
  `userID` CHAR(36) NOT NULL,
  `boardID` CHAR(10) NOT NULL,
  `permission` VARCHAR(45) NULL DEFAULT 'user',
  PRIMARY KEY (`userID`, `boardID`),
  INDEX `boardID` (`boardID` ASC) VISIBLE,
  CONSTRAINT `board_permissions_ibfk_1`
    FOREIGN KEY (`userID`)
    REFERENCES `itbkk-kk3`.`users` (`userID`)
    ON DELETE CASCADE,
  CONSTRAINT `board_permissions_ibfk_2`
    FOREIGN KEY (`boardID`)
    REFERENCES `itbkk-kk3`.`boards` (`boardID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itbkk-kk3`.`boards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `itbkk-kk3`.`boards` ;

CREATE TABLE IF NOT EXISTS `itbkk-kk3`.`boards` (
  `boardID` CHAR(10) NOT NULL,
  `boardName` VARCHAR(120) NOT NULL,
  `ownerID` CHAR(36) NOT NULL,
  PRIMARY KEY (`boardID`),
  INDEX `ownerID` (`ownerID` ASC) VISIBLE,
  CONSTRAINT `boards_ibfk_1`
    FOREIGN KEY (`ownerID`)
    REFERENCES `itbkk-kk3`.`users` (`userID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itbkk-kk3`.`statuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `itbkk-kk3`.`statuses` ;

CREATE TABLE IF NOT EXISTS `itbkk-kk3`.`statuses` (
  `statusID` INT NOT NULL AUTO_INCREMENT,
  `statusName` VARCHAR(50) NOT NULL,
  `statusDescription` VARCHAR(200) NULL DEFAULT NULL,
  `boardID` CHAR(10) NOT NULL,
  PRIMARY KEY (`statusID`),
  UNIQUE INDEX `statusName` (`statusName` ASC, `boardID` ASC) VISIBLE,
  INDEX `boardID` (`boardID` ASC) VISIBLE,
  CONSTRAINT `statuses_ibfk_1`
    FOREIGN KEY (`boardID`)
    REFERENCES `itbkk-kk3`.`boards` (`boardID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 324
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itbkk-kk3`.`tasks`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `itbkk-kk3`.`tasks` (
  `taskID` INT NOT NULL AUTO_INCREMENT,
  `taskTitle` VARCHAR(100) NOT NULL,
  `taskDescription` VARCHAR(500) NULL DEFAULT NULL,
  `taskStatus` INT NOT NULL,
  `boardID` CHAR(10) NOT NULL,
  `createdOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `taskAssignees` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`taskID`),
  INDEX (`taskStatus`),
  INDEX (`boardID`),
  CONSTRAINT `tasks_ibfk_1`
    FOREIGN KEY (`taskStatus`)
    REFERENCES `itbkk-kk3`.`statuses` (`statusID`),
  CONSTRAINT `tasks_ibfk_2`
    FOREIGN KEY (`boardID`)
    REFERENCES `itbkk-kk3`.`boards` (`boardID`)
    ON DELETE CASCADE
)
ENGINE = InnoDB
AUTO_INCREMENT = 161
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



-- -----------------------------------------------------
-- Table `itbkk-kk3`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `itbkk-kk3`.`users` ;

CREATE TABLE IF NOT EXISTS `itbkk-kk3`.`users` (
  `userID` CHAR(36) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `itbkk-kk3`;

DELIMITER $$

USE `itbkk-kk3`$$
DROP TRIGGER IF EXISTS `itbkk-kk3`.`after_insert_board` $$
USE `itbkk-kk3`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `itbkk-kk3`.`after_insert_board`
AFTER INSERT ON `itbkk-kk3`.`boards`
FOR EACH ROW
BEGIN
    -- Insert 4 default statuses for the newly inserted board
    INSERT INTO statuses (statusName, statusDescription, boardID)
    VALUES ('No Status', 'Tasks that need to be done', NEW.boardID),
           ('To Do', 'Tasks currently being worked on', NEW.boardID),
           ('Doing', 'Tasks under review', NEW.boardID),
           ('Done', 'Completed tasks', NEW.boardID);
END$$


USE `itbkk-kk3`$$
DROP TRIGGER IF EXISTS `itbkk-kk3`.`before_insert_and_update_tasks` $$
USE `itbkk-kk3`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `itbkk-kk3`.`before_insert_and_update_tasks`
BEFORE INSERT ON `itbkk-kk3`.`tasks`
FOR EACH ROW
BEGIN
    IF NEW.taskTitle IS NOT NULL THEN
        SET NEW.taskTitle = TRIM(NEW.taskTitle);
    END IF;
    
    IF NEW.taskDescription IS NOT NULL THEN
        SET NEW.taskDescription = TRIM(NEW.taskDescription);
    END IF;
END$$


USE `itbkk-kk3`$$
DROP TRIGGER IF EXISTS `itbkk-kk3`.`update_updatedOn_before_updates` $$
USE `itbkk-kk3`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `itbkk-kk3`.`update_updatedOn_before_updates`
BEFORE UPDATE ON `itbkk-kk3`.`tasks`
FOR EACH ROW
BEGIN
    SET NEW.updatedOn = UTC_TIMESTAMP();
END$$


DELIMITER ;
